dist: trusty
language: android
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
    - build-tools-28.0.3
    - android-28
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build"
- "./gradlew test"
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true
    repo: sphrak/Flowkprefs
