dist: trusty
language: java
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build"
- "./gradlew test"
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true
    repo: sphrak/Flowkprefs
