dist: trusty
language: android
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
    - build-tools-29.0.3
    - android-29
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"
  - chmod +x gradlew
script:
- "./gradlew clean ktlint assembleRelease"
- "./gradlew test"
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true
    repo: sphrak/Flowkprefs
